import axios from 'axios'
import Head from 'next/head'
import Navigation from '../src/components/Layout/Navigation'
import HomeScreen from '../src/screens/Home'

interface Props {
  products: Array<any>
}

export async function getStaticProps() {
  const { data } = await axios.get('/admin/product/get')

  return {
    props: {
      products: data
    },
    revalidate: 60
  }
}

const Home = ({ products }: Props) => {
  return (
    <>
      <Head>
        <title>Arteiz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navigation />
      <HomeScreen data={products} />
    </>
  )
}

export default Home
